import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "./components/ui/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          <div>
            <Navbar></Navbar>
            {children}
          </div>
      </body>
    </html>
  );
}